import Head from 'next/head'

const head = () => {
    return (
        <Head>
            <title>Tribute Page</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" />
            <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500;700;display=swap" rel="stylesheet" />
        </Head>
    );
};

export default head;

